name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Deploy to Google Cloud
        run: |
          echo ${{ secrets.GCLOUD_SERVICE_KEY }} | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project ${{ secrets.GCLOUD_PROJECT_ID }}
          gcloud app deploy --quiet
